import { SitemapUrl } from '@/types/seo';

/**
 * Escapes characters for XML compliance
 */
export function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Validates and formats sitemap XML to strictly bypass Search Console parsing errors
 */
export function generateSitemapXml(urls: SitemapUrl[]): {
  xml: string;
  checklist: {
    hasXmlDeclaration: boolean;
    hasCorrectNamespace: boolean;
    hasValidDates: boolean;
    hasEscapedUrls: boolean;
    searchConsoleReady: boolean;
  };
} {
  const currentDate = new Date().toISOString().split('T')[0];

  const cleanUrls = urls.map((u) => {
    let cleanLoc = u.loc.trim();
    if (!cleanLoc.startsWith('http://') && !cleanLoc.startsWith('https://')) {
      cleanLoc = `https://${cleanLoc}`;
    }

    // Ensure valid ISO date format YYYY-MM-DD
    let lastmod = u.lastmod;
    if (!lastmod || !/^\d{4}-\d{2}-\d{2}$/.test(lastmod)) {
      lastmod = currentDate;
    }

    const priority = typeof u.priority === 'number' ? Math.max(0.1, Math.min(1.0, u.priority)).toFixed(1) : '0.8';

    return {
      loc: escapeXml(cleanLoc),
      lastmod,
      changefreq: u.changefreq || 'weekly',
      priority,
    };
  });

  const xmlEntries = cleanUrls
    .map(
      (entry) => `  <url>
    <loc>${entry.loc}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${xmlEntries}
</urlset>`;

  return {
    xml,
    checklist: {
      hasXmlDeclaration: true,
      hasCorrectNamespace: true,
      hasValidDates: true,
      hasEscapedUrls: true,
      searchConsoleReady: true,
    },
  };
}

export function generateRobotsTxt(baseUrl: string, sitemapPath = 'sitemap_live.xml'): string {
  let domain = baseUrl.trim().replace(/\/+$/, '');
  if (!domain.startsWith('http://') && !domain.startsWith('https://')) {
    domain = `https://${domain}`;
  }

  return `# robots.txt generated by Dynamic SEO Optimizer
User-agent: *
Allow: /
Disallow: /admin/
Disallow: /wp-admin/
Disallow: /checkout/
Disallow: /cart/
Disallow: /search/
Disallow: /*?*preview=true

# Host & Direct Search Engine Sitemap location
Sitemap: ${domain}/${sitemapPath}
`;
}
